// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: 'AIzaSyAv4f84Hy4eBHnZFOzY-jqH6sK9cOtrCtg',
  appId: '1:241168593665:web:8372ad383b9a1a5f03e100',
  messagingSenderId: '241168593665',
  projectId: 'login-579fd',
  authDomain: 'login-579fd.firebaseapp.com',
  storageBucket: 'login-579fd.appspot.com',
);


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASnXxcNFn9rF7gdYq8EWPG56KCVmaGhM8',
    appId: '1:241168593665:android:9579b486c328cfc003e100',
    messagingSenderId: '241168593665',
    projectId: 'login-579fd',
    storageBucket: 'login-579fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Bjv0UXR5WXokFc4yj4AcgsgH0T_5HVI',
    appId: '1:241168593665:ios:67aa82ba2723148703e100',
    messagingSenderId: '241168593665',
    projectId: 'login-579fd',
    storageBucket: 'login-579fd.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppBienestar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6Bjv0UXR5WXokFc4yj4AcgsgH0T_5HVI',
    appId: '1:241168593665:ios:67aa82ba2723148703e100',
    messagingSenderId: '241168593665',
    projectId: 'login-579fd',
    storageBucket: 'login-579fd.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppBienestar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv4f84Hy4eBHnZFOzY-jqH6sK9cOtrCtg',
    appId: '1:241168593665:web:2ec90e512d241cc803e100',
    messagingSenderId: '241168593665',
    projectId: 'login-579fd',
    authDomain: 'login-579fd.firebaseapp.com',
    storageBucket: 'login-579fd.firebasestorage.app',
  );
}
